import type { Metadata } from "next";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="m-2">
        <header className="bg-slate-400 p-[1rem]">
          <p>Header</p>
        </header>
        {children}
        <footer className="bg-red-100 p-4">
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
